version: "3.8"
services:
  openvpn:
    image: alekslitvinenk/openvpn:#{OVPN_VERSION openvpn image version required}
    hostname: ${OVPN_NAME:? openvpn name required}
    container_name: ${OVPN_NAME:? openvpn name required}
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE:? timezone required}
      - HOST_ADDR= ${OVPN_HOST_ADDR} 
    ports:
      - 1194:1194/udp # Expose tcp if you defined HOST_TUN_PROTOCOL=tcp
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn:/opt/Dockovpn_data:rw