version: "3.8"
services:
  pihole:
    image: pihole/pihole:${PIHOLE_IMAGE_VERSION:? pihole image version required} 
    hostname: ${PIHOLE_NAME:? pihole name required}
    container_name: ${PIHOLE_NAME:? pihole name required}
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE:? timezone required}
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD:? pihole web password required}
      - DHCP_ROUTER=${PIHOLE_DHCP_ROUTER:? pihole dhcp router required}
      - DHCP_LEASETIME=${PIHOLE_DHCP_LEASETIME:? pihole dhcp leasetime required}
      - PIHOLE_DOMAIN=${PIHOLE_DOMAIN:? pihole domain name required}
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pihole/etc-pihole:/etc/pihole:rw
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d:rw
    networks:
      - pihole