version: '3.8' 
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    hostname: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - TZ=Europe/Amsterdam
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql