version: '3.8'
services:
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy
    hostname: proxy
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt