version: "3.8"
services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:${WIREGUARD_IMAGE_VERSION:? wireguard image version required}
    hostname: ${WIREGUARD_NAME:? wireguard name required}
    container_name: ${WIREGUARD_NAME:? wireguard name required}
    environment:
      - PASSWORD=<PASSWORD>
      - WG_HOST=${WIREGUARD_HOST_ADDR}
    volumes:
      - ./wireguard/config:/etc/wireguard
    ports:
      - 51820:51820/udp  # Port for vpn connection
      - 51821:51821/tcp  # Port for config interface
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
